/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import model.User;
import javax.swing.*;
import java.awt.Color;
import javax.swing.JTextArea;
import java.util.Date;


/**
 *
 * @author demi
 */
public class ViewJPanel extends javax.swing.JPanel {
    
    private javax.swing.JLabel photoDisplayLabel; 

    /**
     * Creates new form ViewJPanel
     */
    public ViewJPanel() {
        initComponents();
        setupComponents();
    }
    
    private void setupComponents() {
        FirstNameTextField.setEnabled(false);
        LastNameTextField.setEnabled(false);
        AgeSpinner.setEnabled(false);
        PhoneFormattedTextField.setEnabled(false);
        EmailFormattedTextField.setEnabled(false);
        ContinentComboBox.setEnabled(false);
        jDateChooser1.setEnabled(false);
        jDateChooser1.getCalendarButton().setEnabled(false);
        
        
            JTextArea hobbyArea = (JTextArea) jScrollPane1.getViewport().getView();
            hobbyArea.setEditable(false);
            
            Color grayBg = new Color(240, 240, 240);
            FirstNameTextField.setBackground(grayBg);
            LastNameTextField.setBackground(grayBg);
            AgeSpinner.setBackground(grayBg);
            PhoneFormattedTextField.setBackground(grayBg);
            EmailFormattedTextField.setBackground(grayBg);
            ContinentComboBox.setBackground(grayBg);
            jDateChooser1.setBackground(grayBg);
            hobbyArea.setBackground(grayBg);
            
            if (photoDisplayLabel != null) {
                photoDisplayLabel.setBorder(BorderFactory.createLineBorder(Color.GRAY));
                photoDisplayLabel.setHorizontalAlignment(SwingConstants.CENTER);
                photoDisplayLabel.setText("No Photo");
            }
    }
    
    public void displayUser(User user) {
        if (user == null) {
            clearFields();
            return;
        }
        
        
        FirstNameTextField.setText(user.getFirstName());
        LastNameTextField.setText(user.getLastName());
        AgeSpinner.setValue(user.getAge());
        PhoneFormattedTextField.setText(user.getPhone());
        EmailFormattedTextField.setText(user.getEmail());
        ContinentComboBox.setSelectedItem(user.getContinent());
        
        if (user.getDateOfBirth() != null) {
            jDateChooser1.setDate(user.getDateOfBirth());
        } else {
            jDateChooser1.setDate(null);
        }
        
        JTextArea hobbyArea = (JTextArea) jScrollPane1.getViewport().getView();
        hobbyArea.setText(user.getHobby());
        
        if (user.getPhoto() != null && photoDisplayLabel != null) {
            photoDisplayLabel.setIcon(new ImageIcon(user.getPhoto()));
            photoDisplayLabel.setText("");
        } else if (photoDisplayLabel != null) {
            photoDisplayLabel.setIcon(null);
            photoDisplayLabel.setText("No Photo");
        }
    }
        
    
    private void clearFields() {
        FirstNameTextField.setText("");
        LastNameTextField.setText("");
        AgeSpinner.setValue(0);
        PhoneFormattedTextField.setText("");
        EmailFormattedTextField.setText("");
        ContinentComboBox.setSelectedItem(null);
        jDateChooser1.setDate(null);
        
        JTextArea hobbyArea = (JTextArea) jScrollPane1.getViewport().getView();
        hobbyArea.setText("");
        
        if (photoDisplayLabel != null) {
            photoDisplayLabel.setIcon(null);
            photoDisplayLabel.setText("No Photo");
        }
    }

    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StudentDetails = new javax.swing.JLabel();
        FirstName = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        Age = new javax.swing.JLabel();
        Phone = new javax.swing.JLabel();
        Continent = new javax.swing.JLabel();
        Hobby = new javax.swing.JLabel();
        FirstNameTextField = new javax.swing.JTextField();
        LastNameTextField = new javax.swing.JTextField();
        AgeSpinner = new javax.swing.JSpinner();
        PhoneFormattedTextField = new javax.swing.JFormattedTextField();
        ContinentComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        HobbyTextArea = new javax.swing.JTextArea();
        Email = new javax.swing.JLabel();
        EmailFormattedTextField = new javax.swing.JFormattedTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        StudentDetails.setText("Student Details");

        FirstName.setText("First Name:");

        LastName.setText("Last Name:");

        Age.setText("Age:");

        Phone.setText("Phone:");

        Continent.setText("Continent:");

        Hobby.setText("Hobby:");

        FirstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameTextFieldActionPerformed(evt);
            }
        });

        PhoneFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneFormattedTextFieldActionPerformed(evt);
            }
        });

        ContinentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Africa", "Asia", "Australia", "Antarctica", "Europe", "North America", "South America" }));

        HobbyTextArea.setColumns(20);
        HobbyTextArea.setRows(5);
        jScrollPane1.setViewportView(HobbyTextArea);

        Email.setText("Email:");

        EmailFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailFormattedTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(StudentDetails))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(FirstName)
                                .addGap(18, 18, 18)
                                .addComponent(FirstNameTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Phone)
                                            .addComponent(Hobby)
                                            .addComponent(Continent)
                                            .addComponent(Email))
                                        .addGap(26, 26, 26))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(LastName)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ContinentComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LastNameTextField)
                                        .addComponent(AgeSpinner)
                                        .addComponent(PhoneFormattedTextField)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                                        .addComponent(EmailFormattedTextField)))))))
                .addContainerGap(333, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(StudentDetails)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstName)
                    .addComponent(FirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastName))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Age)
                    .addComponent(AgeSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email)
                    .addComponent(EmailFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Phone))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Continent)
                    .addComponent(ContinentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(Hobby))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FirstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameTextFieldActionPerformed

    private void PhoneFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneFormattedTextFieldActionPerformed

    private void EmailFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailFormattedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailFormattedTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Age;
    private javax.swing.JSpinner AgeSpinner;
    private javax.swing.JLabel Continent;
    private javax.swing.JComboBox<String> ContinentComboBox;
    private javax.swing.JLabel Email;
    private javax.swing.JFormattedTextField EmailFormattedTextField;
    private javax.swing.JLabel FirstName;
    private javax.swing.JTextField FirstNameTextField;
    private javax.swing.JLabel Hobby;
    private javax.swing.JTextArea HobbyTextArea;
    private javax.swing.JLabel LastName;
    private javax.swing.JTextField LastNameTextField;
    private javax.swing.JLabel Phone;
    private javax.swing.JFormattedTextField PhoneFormattedTextField;
    private javax.swing.JLabel StudentDetails;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
